### ISSUE TITLE
Svelte 5 support

### ISSUE THREAD

**Issue by secondme2** [jill64/svelte-dark-theme#510]
Thank you for this library! Any chances that Svelte 5 will be supported? Currently, installation gives this error:

```
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@"^4.0.0" from @jill64/svelte-dark-theme@2.3.43
npm ERR! node_modules/@jill64/svelte-dark-theme
npm ERR!   @jill64/svelte-dark-theme@"*" from the root project
```

**Comment by jill64** [comment]
Thank you for opening this issue!
Svelte5 is currently in beta and is subject to breaking changes without notice, so it cannot be officially supported by this library yet.
However, this error is a problem caused by `peerDependencies`, so installing the dependency with the `--legacy-peer-deps` option may temporarily resolve the issue.

```sh
npm i --legacy-peer-deps
````

This library will also be updated when Svelte5 is officially released.
